# Generated by Django 3.0.2 on 2020-02-18 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Polar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polar', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('chorus', models.TextField()),
                ('hook', models.TextField()),
                ('lead', models.TextField()),
                ('year', models.CharField(max_length=4)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LyricsMood.Artists')),
                ('polar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LyricsMood.Polar')),
            ],
        ),
    ]
